#%%
#Ativiade01
print("="*30)
num = int(input("Digite um numero: "))
ant = num - 1 
suc = num + 1 
print(f'O seu antecessor é: {ant} e o sucessor: {suc}')

#%%
#Atividade02
print("="*30)
num = int(input("Digite um numero: "))
dob = num * 2 
tri = num * 3
rai = num ** (1/2)
print(f"O dobro desse numero é {dob}, o tlipo {tri} e a raiz é {rai}.")

#%%
#Atividade03
print("="*30)
nota01 = int(input("Nota um: "))
nota02 = int(input("Nota dois: "))
media = (nota01 + nota02) / 2 
print(f"A sua média é: {media}.")

#%%
#Atividade04
print("="*30)
valor = int(input("Digite um valor em mentros: "))
cm = valor * 10 * 10
mm = valor * 10 * 10 * 10 
print(f"O valor convertido em centímentos é {cm}cm e em milímetro {mm}mm.")

#%%
#Atividade05
print("="*30)
tab = int(input("Digite um numero: "))
mult01 = tab * 1
mult02 = tab * 2 
mult03 = tab * 3
mult04 = tab * 4 
mult05 = tab * 5
mult06 = tab * 6
mult07 = tab * 7
mult08 = tab * 8 
mult09 = tab * 9 
mult010 = tab * 10
print(f"A tabuada de multiprica desse número é: \n {tab}x1 = {mult01} \n {tab}x2 = {mult02} \n {tab}x3 = {mult03} \n {tab}x4 = {mult04} \n {tab}x5 = {mult05} \n {tab}x6 = {mult06} \n {tab}x7 = {mult07} \n {tab}x8 = {mult08} \n {tab}x9 = {mult09} \n {tab}x10 = {mult010}")

#%%
#Atividade06
print("="*30)
din = int(input("Qual o valor da sua carteira? "))
dolla = din * 5.42
print(f"O valor em Dollar é: {dolla}$")

#%%
#Atividade07
print("="*30)
larg = int(input("Qual é a largura da parede? "))
comp = int(input("E o comprimento? "))
area = larg * comp 
tint = area / 2
print(f"vai ser necessario {tint}L de tinta para pinta a parede.")

#%%
#Atividade08 
print("="*30)
preco = int(input("Preço do produto: "))
desc = preco * (5/100)
descf = preco - desc 
print(f"O desconto de 5% desse produto é {descf}.")

#%%
#Atividade09
print("="*30)
salario = int(input("Qual o valor do seu salario? "))
aumt = salario * (15/100)
aumtf = salario + aumt
print(f"O aumento de 15% no salario é {aumtf}.")